export const folders = [
  {
    id: 1,
    "De-identify": "A1",
    "Total Images": 1500,
    "Scan / Series": 10,
    Modality: "MR",
    Gender: "M",
    Age: 12,
    Protocols: 16,
    "Duration of Scan": 45,
    "Date of Scan": "12/02/2008",
    Scanner: "Cannon",
  },
  {
    id: 2,
    "De-identify": "A2",
    "Total Images": 1900,
    "Scan / Series": 13,
    Modality: "MR",
    Gender: "M",
    Age: 11,
    Protocols: 13,
    "Duration of Scan": 40,
    "Date of Scan": "02/02/2009",
    Scanner: "Cannon",
  },
  {
    id: 3,
    "De-identify": "A3",
    "Total Images": 1300,
    "Scan / Series": 13,
    Modality: "MR",
    Gender: "M",
    Age: 17,
    Protocols: 16,
    "Duration of Scan": 47,
    "Date of Scan": "02/10/2010",
    Scanner: "Siemens",
  },
  {
    id: 4,
    "De-identify": "A4",
    "Total Images": 1100,
    "Scan / Series": 64,
    Modality: "MR",
    Gender: "F",
    Age: 11,
    Protocols: 16,
    "Duration of Scan": 45,
    "Date of Scan": "12/09/2012",
    Scanner: "Siemens",
  },
  {
    id: 5,
    "De-identify": "A5",
    "Total Images": 1400,
    "Scan / Series": 40,
    Modality: "MR",
    Gender: "F",
    Age: 12,
    Protocols: 16,
    "Duration of Scan": 45,
    "Date of Scan": "12/09/2012",
    Scanner: "Siemens",
  },
  {
    id: 6,
    "De-identify": "A1",
    "Total Images": 1400,
    "Scan / Series": 50,
    Modality: "CT",
    Gender: "F",
    Age: 12,
    Protocols: 16,
    "Duration of Scan": 45,
    "Date of Scan": "12/12/2014",
    Scanner: "Siemens",
  },
  {
    id: 7,
    "De-identify": "A1",
    "Total Images": 1400,
    "Scan / Series": 10,
    Modality: "MR",
    Gender: "M",
    Age: 12,
    Protocols: 16,
    "Duration of Scan": 45,
    "Date of Scan": "12/09/2012",
    Scanner: "Siemens",
  },
  {
    id: 8,
    "De-identify": "A1",
    "Total Images": 1400,
    "Scan / Series": 20,
    Modality: "CT",
    Gender: "M",
    Age: 12,
    Protocols: 16,
    "Duration of Scan": 45,
    "Date of Scan": "05/12/2010",
    Scanner: "Siemens",
  },
  {
    id: 9,
    "De-identify": "A1",
    "Total Images": 1400,
    "Scan / Series": 27,
    Modality: "MR",
    Gender: "M",
    Age: 12,
    Protocols: 16,
    "Duration of Scan": 45,
    "Date of Scan": "02/12/2021",
    Scanner: "Siemens",
  },
  {
    id: 10,
    "De-identify": "A1",
    "Total Images": 1400,
    "Scan / Series": 18,
    Modality: "MR",
    Gender: "M",
    Age: 12,
    Protocols: 16,
    "Duration of Scan": 45,
    "Date of Scan": "05/12/2010",
    Scanner: "Siemens",
  },
  {
    id: 11,
    "De-identify": "A1",
    "Total Images": 1400,
    "Scan / Series": 51,
    Modality: "MR",
    Gender: "M",
    Age: 12,
    Protocols: 16,
    "Duration of Scan": 45,
    "Date of Scan": "05/02/2019",
    Scanner: "Siemens",
  },
  {
    id: 12,
    "De-identify": "A1",
    "Total Images": 1400,
    "Scan / Series": 90,
    Modality: "CT",
    Gender: "M",
    Age: 12,
    Protocols: 16,
    "Duration of Scan": 45,
    "Date of Scan": "12/09/2012",
    Scanner: "Siemens",
  },
];

export const columns = [
  {
    dataField: "id",
    text: "Scan",
    sort: true,
  },
  {
    dataField: "patient_mrn",
    text: "De-identify",
    sort: true,
  },
  {
    dataField: "number_of_images",
    text: "Total Images",
    sort: true,
  },
  {
    dataField: "number_of_series",
    text: "Scan / Series",
    sort: true,
  },
  {
    dataField: "modality",
    text: "Modality",
    sort: true,
  },
  {
    dataField: "patient_sex",
    text: "Gender",
    sort: true,
  },
  {
    dataField: "patient_age",
    text: "Age",
    sort: true,
  },
  {
    dataField: "number_of_protocols",
    text: "# of Protocols",
    sort: true,
  },
  {
    dataField: "duration_of_scan",
    text: "Duration of Scan(ms)",
    sort: true,
  },
  {
    dataField: "date",
    text: "Date of Scan",
    sort: true,
  },
  {
    dataField: "scanner_manufacturer",
    text: "Scanner",
    sort: true,
  },
];
